server:
  port: 9999
  jsp-servlet:
    init-parameters:
      development: true

spring:
  datasource:
    type: org.apache.commons.dbcp.BasicDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud
    username: root
    password: root
  application:
    name: product
  mvc:
    view:
      suffix: .jsp
      prefix: /



mybatis:
  mapper-locations: classpath:com/baizhi/mapper/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka





