server:
  port: 8760
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: zuul
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
management:
  security:
    enabled: false

zuul:
  routes:
    product:
      path: /aa/**
      serviceId: PRODUCT
    aaaa:
      path: /bb/**
      serviceId: ORDER

