eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka
spring:
  application:
    name: springcloud_ribbon_resttemplate_client
server:
  port: 9090

